name: Deploy Hugo Site to Cloudflare Pages

on:
  push:
    branches:
      - main  
      - hugo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version you need

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Build Hugo site
        run: |
          hugo --minify  # Adjust this command if you have specific build options
          # We also need to optimize for prod

      - name: Deploy to Cloudflare Pages
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}  # Set this in your GitHub repository secrets
        run: |
          wrangler publish ./public  # Adjust the path if your output directory is different