/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface Chats {
  chat_id: Generated<string | null>;
  chat_language: Generated<string | null>;
  chat_name: string | null;
  chat_type: Generated<string>;
  creation_date: string | null;
  external_id: string | null;
  has_unread_messages: Generated<number>;
  last_message_date: string | null;
}

export interface ContactChats {
  chat_id: string;
  contact_id: string;
  is_admin: Generated<number>;
  joined_at: string;
}

export interface Contacts {
  chat_app_username: string | null;
  contact_id: Generated<string | null>;
  contact_language: string | null;
  email_address: string | null;
  is_critical: Generated<number>;
  name: string;
  phone_number: string | null;
}

export interface Messages {
  chat_id: string;
  has_media: Generated<number>;
  is_deleted: Generated<number>;
  is_forwarded: Generated<number>;
  media_url: string | null;
  message_embedding: Buffer | null;
  message_id: string;
  message_type: Generated<string>;
  sender_id: string;
  sender_type: Generated<string>;
  sent_date: string;
  text_content: string | null;
}

export interface ReplyTask {
  attempts_count: Generated<number | null>;
  context_data: string | null;
  created_at: string;
  error_message: string | null;
  result_text: string | null;
  retrieval_sources: string | null;
  retrieved_context: string | null;
  status: string;
  task_id: Generated<string | null>;
  updated_at: Generated<string>;
  user_profile_id: string;
}

export interface SchemaMigrations {
  version: string | null;
}

export interface Summary {
  completion_time: string | null;
  error_message: string | null;
  key_conversation_topics_data: string | null;
  metadata_section_data: string | null;
  start_time: string;
  status: string;
  summary_id: Generated<string | null>;
  summary_timestamp: string;
  top_ranked_conversations_data: string | null;
  user_profile_id: string;
}

export interface SummaryPreferences {
  daily_summary_time: Generated<string | null>;
  keywords_enabled: Generated<number>;
  keywords_list: string | null;
  scheduled_summary_times: string | null;
  summarize_chat_types: Generated<string>;
  summary_frequency: Generated<string>;
  summary_preferences_id: Generated<string | null>;
  user_profile_id: string;
  weekly_summary_day: Generated<string | null>;
}

export interface SyncLock {
  latest_update: Generated<string>;
  lock_id: Generated<number | null>;
  lock_status: Generated<number>;
  running_job_id: Generated<string | null>;
}

export interface UserProfile {
  email: string | null;
  name: string;
  preferred_language: Generated<string | null>;
  theme: Generated<string | null>;
  timezone: Generated<string | null>;
  user_profile_id: Generated<string | null>;
}

export interface DB {
  Chats: Chats;
  ContactChats: ContactChats;
  Contacts: Contacts;
  Messages: Messages;
  ReplyTask: ReplyTask;
  schema_migrations: SchemaMigrations;
  Summary: Summary;
  SummaryPreferences: SummaryPreferences;
  SyncLock: SyncLock;
  UserProfile: UserProfile;
}
