name: Deploy Hugo Site to Cloudflare Pages

on:
  push:
    branches: [main, hugo]
    paths:
      - 'hugosite/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: hugosite

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: 'hugosite/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build Hugo site
        env:
          HUGO_ENV: production
        run: |
          hugo --minify --gc

      - name: Install Wrangler
        run: npm install -g wrangler@latest

      - name: Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
        run: |
          wrangler pages deploy public \
            --project-name=${{ vars.CF_PAGES_PROJECT }} \
            --branch=${GITHUB_REF##*/}
