# baseURL = "https://eduardosanzb.dev"
baseURL = "https://laurasanzb.dev/"
languageCode = "en-us"
title = "Laura Sanchez Bautista"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal website of Laura Sanchez - Data Business Analyst"
  author = "Laura Sanchez"
  github = "https://github.com/lausanz"
  linkedin = "https://linkedin.com/in/laura-sanchez-bautista-89217a60"
  email = "hire-me@sanzlau.dev"


[menu]
  [[menu.main]]
    name = "CV"
    url = "https://raw.githubusercontent.com/eduardosanzb/eduardosanzb/master/laura_sanchez.pdf"
    weight = 2
    [menu.main.params]
      icon = 'download'
      download = true
  [[menu.main]]
    name = "Case-Studies"
    pageRef = "/case-studies/"
    weight = 3
    [menu.main.params]
      skip = true
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
    [menu.main.params]
      skip = true
  [[menu.main]]
    name = "Contact"
    url = "/#contact"
    weight = 5
  [[menu.main]]
    name = "Linkedin"
    url = "https://linkedin.com/in/laura-sanchez-bautista-89217a60"
    weight = 6
    [menu.main.params]
      rel = 'external'
      icon = 'linkedin'
  [[menu.main]]
    name = "github"
    url = "https://github.com/lausanz/businessdataanalyst/"
    weight = 7
    [menu.main.params]
      rel = 'external'
      icon = 'github'
  [[menu.mobile]]
    name = "CV"
    url = "https://raw.githubusercontent.com/eduardosanzb/eduardosanzb/master/laura_sanchez.pdf"
    weight = 2
    [menu.mobile.params]
      icon = 'download'
      download = true
  [[menu.mobile]]
    name = "Linkedin"
    url = "https://linkedin.com/in/laura-sanchez-bautista-89217a60"
    weight = 6
    [menu.mobile.params]
      rel = 'external'
      icon = 'linkedin'
  [[menu.mobile]]
    name = "github"
    url = "https://github.com/eduardosanzb/"
    weight = 7
    [menu.mobile.params]
      rel = 'external'
      icon = 'github'
