name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Docker container
        run: |
          docker run --rm --cap-ad=NET_ADMIN eduardosanzb/test-curl
